name: Publish Beta

on:
  release:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+\-beta.[0-9]+
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  publish-npm:
    name: 'Publish to npm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - run: npm run build

      - run: npm publish --dry-run --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
